name: CI/CD for Deckerized Flask App

on:
    push:
        branches: 
        - main
    pull_request:
      branches:
        - main
permissions:
    contents: read

jobs: 
    buil-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'
                
            - name: Install dependencies
              run:  |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Run test
              run:  |
                pytest

    build-and-publish:
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:

            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Docker BUildx
              uses: docker/setup-buildx-action@v2

            - name: login to Docker
              uses: docker/login-action@v2
              with: 
                username: ${{ secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./DocekerFile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME}}/flasktest-app:latest

            - name: Image digest
              run: echo ${{ steps.buil-and-publish.outputs.digest}}
